### ISSUE TITLE
Urllib2 is not in Python3

### ISSUE THREAD

**Issue by kevinhippert** [flowroute/flowroute-sdk-v3-python#15]
Urllib2 is not in python3. 

`  File "c:\flask\unifymn\venv\lib\site-packages\flowroutenumbersandmessaging\controllers\cdrs_controller.py", line 13, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'`

**Comment by FATCAT47** [comment]
Here is a requirements file updated for python 3 I edited
[requirements.txt](https://github.com/flowroute/flowroute-sdk-v3-python/files/4997094/requirements.txt)

**Comment by FATCAT47** [comment]
Instead of "import urllib2" in cdrs_controller.py

try:
from urllib.request import urlopen #For Python 3.0 and later
except ImportError:
from urllib2 import urlopen #For Python 2's urllib2

**Comment by syntaxintact** [comment]
Fix merged
