### ISSUE TITLE
StringIO not in Python3

### ISSUE THREAD

**Issue by kevinhippert** [flowroute/flowroute-sdk-v3-python#16]
StringIO is not in Python3.
It is now in the io library

`  File "c:\flask\unifymn\venv\lib\site-packages\flowroutenumbersandmessaging\controllers\cdrs_controller.py", line 11, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'`

**Comment by FATCAT47** [comment]
Would suggest instead of "import StringIO" in cdrs_controller.py

try:
from StringIO import StringIO ## for Python 2
except ImportError:
from io import StringIO ## for Python 3

**Comment by syntaxintact** [comment]
Fix merged
